### ISSUE TITLE
4.2.1 tekst klopt niet

### ISSUE THREAD

**Issue by NielsHoffmann** [Logius-standaarden/logboek-dataverwerkingen#11]
Om te **optimaliseren voor de het lezen en begrijpen** van de logs is het denkbaar om de benodigde informatie redundant weg te schrijven in elk logrecord, zodat er geen afhankelijkheid bestaat van andere bronnen.

Voorstel:
Om logs zo begrijpelijk mogelijk te maken is het aantrekkelijk om informatie redundant weg te schrijven in elk logrecord, zodat er geen afhankelijkheid bestaat van andere bronnen.

**Comment by mrtn78** [comment]
Dit is een reeds genomen besluit. zie context in par https://logius-standaarden.github.io/logboek-dataverwerkingen/#logregels-bevatten-geen-gegevens-die-al-vastliggen-in-een-register 

- [ ] Te bespreken in het overleg

**Comment by NielsHoffmann** [comment]
@mrtn78 het gaat me niet om het besluit inhoudelijk, maar de zin is krom nederlands...

**Comment by mrtn78** [comment]
fixed in gerelateerde commit.
