### ISSUE TITLE
Bug: Dien een melding - link bijwerken

### ISSUE THREAD

**Issue by Nil-NMB01** [Logius-standaarden/logboek-dataverwerkingen#15]
Alle issuevragen die binnenkomenm moet in de repo van logboek-dataverwerkingen terechtkomen. Op het moment dat je via de respec document zelf op dien een melding drukt van bijvoorbeeld het inleidend document, dan redirect het naar de repo waarvan je het document leest, terwijl alle gerelateerde vragen mbt de standaard via de hoofdrepo (logboek-dataverwerkingen) moeten binnenkomen.

**Comment by mrtn78** [comment]
@sanderke kan jij dit onderzoeken? in het document https://logius-standaarden.github.io/publicatie/api/Logboek_Algemeen/ 
wordt een verwijzing getoond naar de repo van https://github.com/Logius-standaarden/logboek-dataverwerkingen_Juridisch-beleidskader/

in de [config.js](https://github.com/Logius-standaarden/logboek-dataverwerkingen_Inleiding/blob/main/js/config.js) heb ik een verwijzing opgenomen naar de Logboek repo
`  github: "https://github.com/Logius-standaarden/logboek-dataverwerkingen",`

Zie ook het "Doe mee:" onderdeel:
![image](https://github.com/user-attachments/assets/ef0689cf-cf2b-436b-a146-52e78b480c6f)

**Comment by TheBonheurs** [comment]
`const respecConfig = {...organisationConfig, ...localConfig}`

Zou dit nog iets kunnen betekenen, staat in de juridische repo waar deze van is gecloned

**Comment by sanderke** [comment]
> in de [config.js](https://github.com/Logius-standaarden/logboek-dataverwerkingen_Inleiding/blob/main/js/config.js) heb ik een verwijzing opgenomen naar de Logboek repo
> ` github: "https://github.com/Logius-standaarden/logboek-dataverwerkingen",`

Hiermee lijkt het inderdaad opgelost.
