### ISSUE TITLE
Aanpassen voorbeeld 2 bsn's

### ISSUE THREAD

**Issue by synbiaco** [Logius-standaarden/logboek-dataverwerkingen#19]
door nieuwe inzichten moet het voorbeeld worden aangepast.

**Comment by synbiaco** [comment]
Aanpassingen aan voorbeeld kunnen worden doorgevoerd. Het document staat op https://www.samenwerkruimten.nl/teamsites/project%20verwerkingenlogging/_layouts/15/WopiFrame.aspx?sourcedoc=%7BFAB71607-1794-4276-9B59-3757FB04DCB3%7D&file=Registratie%20Verhuizing%20%E2%80%93%20opvragen%20meerdere%20BSN%27s.docx&action=default&IsList=1&ListId=%7BC0637601-7B4C-4198-9A94-CCB6D5108D53%7D&ListItemId=112. De wijzigingen staan in het rood, ook het relatiediagram moet worden vervangen (nieuwe diagram staat in het document).

**Comment by Nil-NMB01** [comment]
@mrtn78 Als je het document opent in Word, zie je de wijzigingen pas.

**Comment by Nil-NMB01** [comment]
Nu snap ik wat er bedoeld wordt wanneer mensen zeggen dat bestaande wijzigingen soms meer tijd kunnen duren dan nieuwe wijzigingen.
