### ISSUE TITLE
Scope aanpassen in standaarddocument

### ISSUE THREAD

**Issue by synbiaco** [Logius-standaarden/logboek-dataverwerkingen#20]
verduidelijking scope nodig voor de loggingstandaard

**Comment by synbiaco** [comment]
scope opgeleverd in concept, maandag 18 nov overleg.

**Comment by synbiaco** [comment]
tekst van het document kan gepubliceerd worden. Het document staat hier: https://www.samenwerkruimten.nl/teamsites/project%20verwerkingenlogging/_layouts/15/WopiFrame.aspx?sourcedoc=%7B5B566831-5432-48E3-8B4A-D2B3307B31B3%7D&file=Scope%20standaard_SK%20edits.docx&action=default&IsList=1&ListId=%7BC0637601-7B4C-4198-9A94-CCB6D5108D53%7D&ListItemId=117. De tekst moet toegevoegd worden aan de standaard, wellicht kunnen jullie kijken naar de andere standaarden en zeelf bepalen wat een logische plek is om de tekst neer te zetten. LET OP: er zijn 2 verwijzigingen naar de besluiten (4.5 en 4.6) voor zover ik weet is er nog geen aparte plaats gemaakt voor de besluiten, tzt moeten deze verwijzigingen gelinkt worden aan de desbetreffende besluiten.

**Comment by Nil-NMB01** [comment]
@mrtn78 Heel hoofdstuk 4 met besluiten is wegegooid, maar deze changes zijn bedoeld t.b.v. de besluiten van hoofdstuk 4. Hoe wordt dit nu opgepakt?

**Comment by Nil-NMB01** [comment]
Gewoon in inleidend document doorvoeren.
