### ISSUE TITLE
Aanmaken uitleg tav tracing

### ISSUE THREAD

**Issue by synbiaco** [Logius-standaarden/logboek-dataverwerkingen#21]

**Comment by mrtn78** [comment]
Voorlopig alleen opnemen in de inleiding

**Comment by Nil-NMB01** [comment]
ben ermee bezig

**Comment by Nil-NMB01** [comment]
Hi @mrtn78 , tekst staat klaar, maar de vraag is waar in de inleiding dit terecht moet?
https://github.com/Logius-standaarden/logboek-dataverwerkingen_Inleiding/blob/main/relatie_logboekelementen.md

Hetzelfde geldt voor het tekst wat @synbiaco deronder heeft toegevoegd ""Het veld attributes is een lijst van key-value pairs, in een namespace met prefix dpl. (data processing log). De volgende attributen zijn mogelijk in de namespace core:

dpl.core.processing_activity_id: URI; Verwijzing naar register met meer informatie over de verwerkingsactiviteit
dpl.core.data_subject_id: ID van de Betrokkene; versleuteld. Dit is bijvoorbeeld een BSN of Vreemdelingennummer waarmee wordt aangeduid welke persoon Betrokkene is bij de verwerking, gelet op de AVG."

In het document 'De relatie tussen logboekelementen, waarom eigenlijk?' wordt stap voor stap uitgelegd hoe het traceringsmechanisme werkt." Waar mag dit toegevoegd worden?

**Comment by Nil-NMB01** [comment]
Changes doorgevoerd:

https://logius-standaarden.github.io/publicatie/api/Logboek_Algemeen/#de-relatie-tussen-logboekelementen-waarom-eigenlijk
