### ISSUE TITLE
Uniformeren terminologie (voorstel pieter)

### ISSUE THREAD

**Issue by synbiaco** [Logius-standaarden/logboek-dataverwerkingen#22]

**Comment by synbiaco** [comment]
Aanpassingen aan tekst standaard kunnen worden geimplementeerd (zie bijgaand document)
[Logboek dataverwerkingen_aanpassingen.docx](https://github.com/user-attachments/files/17733107/Logboek.dataverwerkingen_aanpassingen.docx)

**Comment by Nil-NMB01** [comment]
Doornemen met Jeroen aankomende donderdag.

**Comment by Nil-NMB01** [comment]
In overleg laten zoals het is.
