### ISSUE TITLE
Betrokkene / dplCoreDataSubjectId => in het kader van dataverwerkingen voor (geo) objecten gaat dit niet over natuurlijke personen

### ISSUE THREAD

**Issue by NielsHoffmann** [Logius-standaarden/logboek-dataverwerkingen#29]
Wat mij betreft komt de discrepantie het sterkst naar voren in de beschrijving van de extensie 'inzage' (in de standaard zelf). 

_Extensie Inzage
Deze extensie heeft een afhankelijkheid van de extensies [Betrokkenen](https://logius-standaarden.github.io/logboek-dataverwerkingen/#dfn-betrokkenen) en Verwerkte Data, en biedt een interface op de logs vanuit het perspectief van de [Betrokkene](https://logius-standaarden.github.io/logboek-dataverwerkingen/#dfn-betrokkenen)._

Vanuit (geo)objecten bezien is inzage ook van belang voor (ethische) verantwoording van toepassing van een bepaald algoritme.

**Comment by Nil-NMB01** [comment]
Mijn suggestie: 

Wanneer data wordt verwerkt, wordt de entiteit waarvan de overheidsorganisatie data verwerkt de 'Betrokkene' genoemd. Dit is degene of de entiteit over wie of wat de dataverwerking gaat. De Betrokkene is degene of de entiteit waarop een gegeven betrekking heeft en die daarmee geïdentificeerd kan worden. Als identificeerbaar wordt beschouwd een entiteit die direct of indirect kan worden geïdentificeerd, met name aan de hand van een identificator zoals een naam, een identificatienummer, locatiegegevens, een online identificator of van een of meer elementen die kenmerkend zijn voor de fysieke, fysiologische, genetische, psychische, economische, culturele of sociale identiteit van die entiteit [NORA: De Privacy Baseline/Persoonsgegevens en bijzondere persoonsgegevens].

**Comment by mrtn78** [comment]
Voorgestelde tekstwijziging:

**Betrokkene**

Als data wordt verwerkt, wordt de (niet natuurlijke) persoon van wie de overheidsorganisatie (persoons)gegevens verwerkt de 'Betrokkene' genoemd. Dat is dus degene over wie de dataverwerking gaat. De Betrokkene is degene op wie de data betrekking heeft en die daarmee geïdentificeerd kan worden. Als identificeerbaar wordt beschouwd een natuurlijk of niet natuurlijk  persoon die direct of indirect kan worden geïdentificeerd, met name aan de hand van een identificator zoals een naam, een identificatienummer, locatiegegevens, een online identificator of van een of meer elementen die kenmerkend zijn voor de fysieke, fysiologische, genetische, psychische, economische, culturele of sociale identiteit van die natuurlijke persoon [NORA: De Privacy Baseline/Persoonsgegevens en bijzondere persoonsgegevens](https://www.noraonline.nl/wiki/De_Privacy_Baseline/Persoonsgegevens_en_bijzondere_persoonsgegevens)

**Comment by Nil-NMB01** [comment]
Toewijzen aan Vedran.

**Comment by NielsHoffmann** [comment]
Het gaat mij niet in eerste instantie om de definitie van betrokkene. Het gaat om de toelichting bij de extensie inzage. Dat is niet alleen inzage vanuit het perspectief van een betrokkene, maar kan ook inzage vanuit het perspectief van een (geo)object zijn.

**Comment by VBZK** [comment]
Ik denk dat ik het eens ben met Niels. Waarbij ik me afvraag of inzage extensie misschien ook inzage moet bieden vanuit het perspectief van verwerkte data in het algemeen. Bijv. zou inzage extensie ook een antwoord moeten kunnen geven op de vraag "wie heeft allemaal deze adres bekeken"? Ik kan nu niet direct de consequenties daarvan overzien. Daarom stel ik voor dat we de tekst algemeen houden totdat er meer duidelijkheid is over hoe de inzage module eruit komt te zien. Bijv.:

"Deze extensie heeft een afhankelijkheid van de extensies [Betrokkenen](https://logius-standaarden.github.io/logboek-dataverwerkingen/#dfn-betrokkenen) en Verwerkte Data, en biedt een interface op de logs vanuit _EEN BEPAALD_ perspectief."

**Comment by VBZK** [comment]
Op zich snap ik je punt maar ik zou het nu niet doen. Een niet natuurlijk persoon heeft volgens mij geen recht op inzage, vanuit AVG gezien. 
Van Eelco begrijp ik  dat hij de betrokkene even gericht op AVG wil hebben en mogelijk ook die inzage extensie. Inzage vanuit andere perspectieven wil hij wellicht anders oplossen. Laten we dat een keer in een sessie bespreken. 
Dus voor nu: laat het staan zoals het was.

**Comment by mrtn78** [comment]
oke, dan is deze verder klaar
