### ISSUE TITLE
Github van Geonovum toevoegen

### ISSUE THREAD

**Issue by VBZK** [Logius-standaarden/logboek-dataverwerkingen#34]
Belangrijk werk irt de uitbreiding van de standaard gebeurt op de github van Geonovum. Voeg die ajb toe aan de verwijzingen: https://geonovum.github.io/logboek-dataverwerkingen-voor-objecten/.

**Comment by Nil-NMB01** [comment]
Waar in de readme kan ik hem het best toevoegen? @mrtn78

**Comment by mrtn78** [comment]
Deze readme zit in alle repo's.
- [ ] https://github.com/Logius-standaarden/logboek-dataverwerkingen/blob/develop/README.md
- [ ] https://github.com/Logius-standaarden/logboek-dataverwerkingen_Inleiding/blob/main/README.md
- [ ] https://github.com/Logius-standaarden/logboek-dataverwerkingen-demo/blob/main/README.md
- [ ] https://github.com/Logius-standaarden/logboek-dataverwerkingen_Juridisch-beleidskader/blob/main/README.md

**Comment by VBZK** [comment]
Klopt het dat ik noch in de readme noch in respec een verwijzing zie naar het werk van Geonovum (hun Respec)? 
Het zou handig zijn als dat te zien is in dat tabel met verwijzingen. Dat is waar deze issue om ging :-)

**Comment by Nil-NMB01** [comment]
Doorgevoerd in de beschrijving en de verwijzing (abstract.md). Het duurt alleen blijkbaar nog even voordat het geüpdate is.

**Comment by Nil-NMB01** [comment]
Changes zijn doorgevoerd. Alleen bij de demo repo is die in de README.md meegenomen, aangezien er geen abstract.md file is. Logisch omdat dit de techniek is en geen documentatie.

https://github.com/Logius-standaarden/logboek-dataverwerkingen/commit/30ab11420e8d9bff3b5d0e341d39c378ee73e610
https://github.com/Logius-standaarden/logboek-dataverwerkingen_Inleiding/commit/d69d5ab9e07a21dae2eacc8df7f3b79f4ca18f58
