### ISSUE TITLE
Voorbeelden overnemen in het inleidende document

### ISSUE THREAD

**Issue by mrtn78** [Logius-standaarden/logboek-dataverwerkingen#4]
De voorbeelden die in de samenwerkruimten door Jeroen zijn gemaakt moeten worden opgenomen in het inleidende document in HS 3. zie ook https://github.com/Logius-standaarden/logboek-dataverwerkingen_Inleiding/blob/main/ch03_voorbeelden.md

**Comment by mrtn78** [comment]
De vier op te nemen voorbeelden zijn:

[Parkeervergunning – Inzien parkeervergunning](https://www.samenwerkruimten.nl/teamsites/project%20verwerkingenlogging/Gedeelde%20%20documenten/Informatieanalyse/Cases/Parkeervergunning_Inzien%20vergunningen.docx?web=1)

[Parkeervergunning – Wijzigen parkeervergunning](https://www.samenwerkruimten.nl/teamsites/project%20verwerkingenlogging/Gedeelde%20%20documenten/Informatieanalyse/Cases/Parkeervergunning_wijzigen%20vergunningen.docx?web=1)

[Registratie verhuizing – Eenvoudig, traditioneel system](https://www.samenwerkruimten.nl/teamsites/project%20verwerkingenlogging/Gedeelde%20%20documenten/Informatieanalyse/Cases/Registratie%20Verhuizing%20%E2%80%93%20Eenvoudig,%20traditioneel%20systeem.docx?web=1)

[Registratie verhuizing – Opvragen meerdere BSN’s](https://www.samenwerkruimten.nl/teamsites/project%20verwerkingenlogging/Gedeelde%20%20documenten/Informatieanalyse/Cases/Registratie%20Verhuizing%20%E2%80%93%20opvragen%20meerdere%20BSN%27s.docx?d=wfab71607179442769b593757fb04dcb3)

**Comment by Nil-NMB01** [comment]
Changes zijn voorlopig doorgevoerd en zijn te vinden op: https://github.com/Logius-standaarden/logboek-dataverwerkingen_Inleiding/blob/main/ch03_voorbeelden.md

**Comment by Nil-NMB01** [comment]
Nog een voorwoord schrijven.

**Comment by Nil-NMB01** [comment]
Voorwoord is geschreven. @mrtn78 Kan jij hem reviewen en bij goedkeuring sluiten?

**Comment by mrtn78** [comment]
Review is akkoord, heb nog wat markdown issues opgelost.
