### ISSUE TITLE
aanpassing FAQ

### ISSUE THREAD

**Issue by MirianvAnsem** [Logius-standaarden/logboek-dataverwerkingen#43]
https://logius-standaarden.github.io/publicatie/api/Logboek_Algemeen/#wie-kan-de-standaard-logboek-dataverwerking-gebruiken

Elke organisatie die gegevens verwerkt kan de standaard Logboek Dataverwerking inzetten bij processen waar logging en monitoring vanuit de wetgeving wenselijk is.

Ik denk dat dit beter is
Elke organisatie die gegevens verwerkt kan de standaard Logboek Dataverwerking inzetten bij processen waar logging en monitoring, bijvoorbeeld vanuit de wetgeving wenselijk is.

**Comment by Nil-NMB01** [comment]
Doorgevoerd: https://github.com/Logius-standaarden/logboek-dataverwerkingen_Inleiding/commit/4c422caf16e468c25c36f4a7864c701c2d7bb596
