### ISSUE TITLE
1.2 dataverwerking

### ISSUE THREAD

**Issue by fterpstra** [Logius-standaarden/logboek-dataverwerkingen#44]
Expliciet aangeven dat een dataverwerking uit één of meerdere operaties kan bestaan (zorg dat je eigen terminologie consistent gebruikt)

**Comment by ehotting** [comment]
Ja, er staat nu 'activiteiten' en het vervelende is dat we 'operations' gaan wijzigen naar 'spans' om beter aan te sluiten bij OTLP. Wellicht even bespreken en een definitieve keuze maken. Is 'operaties' een correcte vertaling van 'operations'? En zo ja, is dat dan de juiste term?

**Comment by ehotting** [comment]
Wordt resolved in #79
