### ISSUE TITLE
Aanpassing FAQ 

### ISSUE THREAD

**Issue by MirianvAnsem** [Logius-standaarden/logboek-dataverwerkingen#45]
https://logius-standaarden.github.io/publicatie/api/Logboek_Algemeen/#is-de-standaard-alleen-bedoeld-voor-de-verwerking-van-persoonsgegevens

Nee, de standaard kan worden toegepast voor andere toepassingen zoals bijvoorbeeld de registratie van (geografische) objecten.

ik denk dat dit beter is
Nee, de standaard kan ook worden gebruikt voor verwerking van andere typen gegevens, zoals bijvoorbeeld de registratie van (geografische) objecten.

**Comment by Nil-NMB01** [comment]
Doorgevoerd: https://github.com/Logius-standaarden/logboek-dataverwerkingen_Inleiding/commit/2c31526abfd3d1547fa0bf850bad48eb0ace3a6d
