### ISSUE TITLE
tekstverbetering FAQ

### ISSUE THREAD

**Issue by mrtn78** [Logius-standaarden/logboek-dataverwerkingen#46]
https://logius-standaarden.github.io/publicatie/api/Logboek_Algemeen/#hoe-werken-het-register-van-verwerkingsactiviteiten-en-het-logboek-dataverwerkingen-samen

In het Register van verwerkingsactiviteiten (art 30 AVG) zijn de binnen de organisatie uit te voeren taken en processen waarin verwerkingen worden uitgevoerd benoemd. In de **Logboek Dataverwerkingen standaard** wordt de relatie gelegd tussen de beschreven processen in het register en de daadwerkelijk uitgevoerde activiteit waarbij **data** zijn verwerkt. **Door deze relatie ontstaat** inzicht in de taak en activiteit waarvoor de **data** verwerkt zijn.

> belangrijkste aanpassingen zijn **bold**

**Comment by Nil-NMB01** [comment]
Changes zijn doorgevoerd: https://github.com/Logius-standaarden/logboek-dataverwerkingen_Inleiding/commit/1116ad0505a71c5f0438a91bfb79b0c8a22a139b
