### ISSUE TITLE
1.3.1 extensies

### ISSUE THREAD

**Issue by fterpstra** [Logius-standaarden/logboek-dataverwerkingen#48]
Het blijft impliciet dat genoemde extensies buiten dit document staan en dat ze (nog) niet gerealiseerd zijn. Alvast placeholders aanmaken en daarnaar verwijzen kan dit mogelijk helder maken of een korte verduidelijkende tekst in een kader.

**Comment by mrtn78** [comment]
uitbreiding opnemen in par https://logius-standaarden.github.io/logboek-dataverwerkingen/#extensies.

verwijzing opnemen naar bijv https://geonovum.github.io/logboek-dataverwerkingen-voor-objecten/
