### ISSUE TITLE
FAQ discrepantie t.o.v. leeswijzer

### ISSUE THREAD

**Issue by MirianvAnsem** [Logius-standaarden/logboek-dataverwerkingen#50]
https://logius-standaarden.github.io/publicatie/api/Logboek_Algemeen/#is-mijn-organisatie-verplicht-de-standaard-logboek-dataverwerking-te-implementeren****

In de leeswijzer staat eerst MIDO-governance, daarna Forum.

Het MIDO deel staat hier niet benoemd.

Welke vaststellingslijn is juist en deze moet hier vermeld worden.

**Comment by mrtn78** [comment]
aanpassen naar :
Er zijn momenteel geen verplichtingen voor gebruik van de standaard. Indien de standaard ooit verplicht wordt zal dit worden gepubliceerd bij het Forum Standaardisatie op de Pas-toe-of-leg-uit-lijst. Hiervoor dient eerst de gehele procedure te worden doorlopen.

**Comment by Nil-NMB01** [comment]
Change doorgevoerd: https://github.com/Logius-standaarden/logboek-dataverwerkingen_Inleiding/commit/12bc236e9e6c15914ddc599bdf1dbc6455eb4327
