### ISSUE TITLE
2.3.1 verwerker niet gedefenieerd in 1.2

### ISSUE THREAD

**Issue by fterpstra** [Logius-standaarden/logboek-dataverwerkingen#56]
Het lijkt me nuttig om de verwerker expliciet in 1.2 te definieren dit is een aparte rol.
In 2.3.1 wordt de verwerkingsverantwoordelijke genoemd als "opdracht van een Verantwoordelijke" hier graag linken naar verwerkingsverantwoordelijke

**Comment by ehotting** [comment]
Wordt opgelost in #79
