### ISSUE TITLE
Verantwoordelijke wordt vaak gebruikt ipv verwerkingsverantwoordelijke

### ISSUE THREAD

**Issue by fterpstra** [Logius-standaarden/logboek-dataverwerkingen#57]
verantwoordelijke wordt vaak gebruikt daar waar verwerkingverantwoordelijke bedoeld lijkt te worden. Terminologie consequent toepassen en linken naar definities.

**Comment by ehotting** [comment]
Eens, het zijn synoniemen in het jargon, formeel is het 'verwerkingsverantwoordelijke' maar ik ben geneigd om dat alleen bij 'terminiologie' uit te schrijven en in het hele document 'Verantwoordelijke' te gebruiken. Meningen?

**Comment by ehotting** [comment]
Nu zo:

`<dfn data-lt="Verantwoordelijke|Verantwoordelijken|Verwerkingsverantwoordelijken">Verwerkingsverantwoordelijke</dfn>

 Een natuurlijke persoon of rechtspersoon, een overheidsinstantie, een dienst of een ander orgaan die/dat, alleen of samen met anderen, het doel van en de middelen voor de verwerking van gegevens vaststelt. Deze definitie is gebaseerd op ([[AVG]] art. 4, lid 7.), maar laat de verantwoordelijkheid betrekking hebben op de verwerking van álle gegevens, niet alleen persoonsgegevens.

 | In de standaard wordt de Verwerkingsverantwoordelijke aangeduid als de Verantwoordelijke voor de leesbaarheid.`

**Comment by ehotting** [comment]
@mrtn78 in het hele document wordt consequent 'Verantwoordelijke' gebruikt behalve in Canoniek gegevensmodel. Kan jij dat in lijn brengen?

**Comment by ehotting** [comment]
Definitie in Terminologie wordt aangepast in #79 , incl. een toelichting op gebruikt 'Verantwoordelijke'

**Comment by mrtn78** [comment]
Alle verwijzingen in de inleiding gewijzigd -> verwerkingsverantwoordelijke vervangen door verantwoordelijke in de FAQ en het Canoniek gegevens model
