### ISSUE TITLE
4. Besluitenlijst - SK review

### ISSUE THREAD

**Issue by shayankhan19988** [Logius-standaarden/logboek-dataverwerkingen#58]
> Deze sectie is tijdelijk en niet normatief, bedoeld om informatie te geven over achterliggende afwegingen bij de standaard --> wat wordt bedoelt met niet normatief? < Dit is gebruikelijk in standaarden
- ? In de definitieve standaard wordt deze lijst niet opgenomen, omdat veel afwegingen specifiek zijn voor de context van de Nederlandse overheid waarin deze standaard is ontstaan. --> als deze niet wordt opgenomen, waarom wordt deze dan vermeld?
- [x] Dit kan door alle organisaties te bevragen, of door gericht bij één organisatie te beginnen en vervolgens de URI's te volgen naar logrecords in andere organisaties. --> wat zijn URI's?
- [x] In logregels wordt alleen een identifier vastgelegd van gerelateerde Dataverwerkingen in een andere context (bijv. een andere organisatie), geen inhoudelijke informatie --> wat is een identifier, of is deze eerder in een begrippenlijst uitgelegd?
- [x] Dat verhoudt zich slecht tot het 'inmutable' zijn van deze logrecords. --> zelfde hier, wat is inmutable?
- [x] staan alle statische gegevens in het Register van de Verwerkingsactiviteiten (RvVA), en bevatten logrecords verwijzigen naar dat Register.--> verwijzingen, typo
- [x] maar een interface te definiëren die kan worden geïmplementeert met bijvoorbeeld gRPC of andere streaming protocollen.--> geïmplementeerd* typo
- [x] Met meer gestandaardiseerde namen en bewaartermijnenen en een eenduidige omgang met vertrouwelijkheid is het ook eenvoudiger om eenduidige te communiceren naar de Betrokkene.--> bewaartermijnen* typo
> en het RvVA bijvoorbeeld alleen bestaat als Excel document.--> wat wordt hiermee bedoeld? Dit is algemeen bekend bij gemeenten die een RvvA hebben
- [x] zonder gestandaardiseerde manier om informatie over verwerkingsactiviteiten op te vragen kan men aan logregels niet zien of het verwerkingen, handelingen of acties betreft. --> zonder een*
- [x] Voor het op betekenisvolle manier tonen van verwerkingen aan bijvoorbeeld een Betrokkene is het dan nodig om gegevens op te vragen uit zowel de logs als het RvVA. -->Om verwerkingen op een significante manier te tonen aan bijvoorbeeld een Betrokkene, is het noodzakelijk om gegevens op te vragen uit zowel de logs als het RvVA.
- [x] Voor samenwerkende organisaties die zich ten doel stellen om gezamenlijk op eenduidige manier te verantwoorden over dataverwerkingen kan het nuttig zijn afspraken voer bewaartermijnen vast te leggen in een Profiel. --> voor*typo
- [x] In gevallen dat het nodig is te achterhalen welke gebruiker een specifieke Dataverwerking heeft uitgevoerd, moet dit worden achterhaald door de Dataverwerking te koppelen aan het Audit Log (buiten scope van de standaard)--> ontbreekt een punt aan eind.
- [x] Er zijn meerdere oplossingsrichtingen denkbaar--> oplossingen is een beter woord. 
- [x] Wanneer een bevraging zowel vertrouwelijk als niet-vetrouwelijk kan zijn (voorbeeld: het opvragen van eigenaargegevens van een voertuig) moeten twee gescheiden processen bestaan, waarbij de vertrouwelijke variant niet alleen apart wordt gelogd, maar in het geheel aan meer strikte regels wordt onderworpen, zoals eisen aan betrokken beheerders, classificatie van gegevens, etc.--> onwijs lange zin, alternatief: Als een bevraging zowel vertrouwelijk als niet-vertrouwelijk kan zijn, zoals bij het opvragen van eigenaargegevens van een voertuig, moeten hiervoor twee gescheiden processen bestaan. De vertrouwelijke variant moet apart worden gelogd en aan strengere regels voldoen. Dit omvat bijvoorbeeld eisen aan betrokken beheerders, de classificatie van gegevens en andere specifieke voorschriften.
- [x] In de logrecords staat zo min mogelijk inhoudelijke informatie (ADR xxx). Informatie over verwerkingsactiviteiten ligt vast in specifieke registers.--> ADR?? < verwijzing en toelichting opnemen over de API Design Rules

**Comment by Nil-NMB01** [comment]
@mrtn78 Hiervoor moeten we nog 1 keer apart even zitten, om te kijken wat er inhoudelijk verdeeld kan worden en tekstueel doorgevoerd.

**Comment by Nil-NMB01** [comment]
Alles is zo goed als doorgevoerd hier behalve voor één punt.

Wat is de definitie van een identifier en hebben we hier al een bestaande bron voor waar we naartoe kunnen verwijzen in het document @mrtn78 @ehotting ?
