### ISSUE TITLE
FAQ uniformiteit

### ISSUE THREAD

**Issue by MirianvAnsem** [Logius-standaarden/logboek-dataverwerkingen#59]
Het is duidelijk zichtbaar dat de FAQ's door verschillende personen zijn geschreven. Laatste deel zeer technisch en weinig begrijpelijk.

Qua uniformiteit. In het eerste deel staat er netjes bij de standaard steeds Logboek dataverwerkingen bij. In het laatste deel is het alleen de standaard. 

Svp overal standaard Logboek Dataverwerkingen gebruiken zodat de teksten ook buiten dit document interpretabel blijven.

**Comment by NielsHoffmann** [comment]
aanvullend hierop. FAQ 2.1.15 mist als kop. (Wat gebeurt er als ik mijn RvvA wil wijzigen na de implementatie van de Logboek Dataverwerkingenstandaard?)
