### ISSUE TITLE
Opzet van de architectuur opnemen

### ISSUE THREAD

**Issue by mrtn78** [Logius-standaarden/logboek-dataverwerkingen#6]
op basis van de FDS platen een eerste schets van de architectuur opnemen mbt de logboek dataverwerkingen positionering

De architectuur daarna aanvullen met content uit de demo repo en verwijzingen opnemen naar gebruikte libraries en dergelijke

**Comment by mrtn78** [comment]
ook in de demo repo is een architectuur model.
verder nog opvragen bij Digilab of ze meer platen hebben.

**Comment by Nil-NMB01** [comment]
Jeroen Mulder toewijzen aan de issue wanneer hij een account heeft.

**Comment by mrtn78** [comment]
De opzet is aangeleverd maar moet nnog in het algemene inleidende document worden verwerkt. Zie het document in https://digilab.overheid.nl/chat/verwerkingenlogging/pl/hbsrowutofyf7r6kianpettnyc

**Comment by synbiaco** [comment]
@mrtn78 @Nil-NMB01 Commentaar wouter toegevoegd, kan worden gepubliceeerd.

**Comment by mrtn78** [comment]
[architectuur - totaal_clean.docx](https://github.com/user-attachments/files/18064349/architectuur.-.totaal_clean.docx)
