### ISSUE TITLE
2.3.4 is gebruiker(medewerker) hetzelfde als verwerker?

### ISSUE THREAD

**Issue by fterpstra** [Logius-standaarden/logboek-dataverwerkingen#60]
Zie titel, zo jo consequent dezelfde terminologie hanteren en verwerker definieren in 1.2

**Comment by ehotting** [comment]
Nee is niet hetzelfde, maar dat moet dan blijkbaar uitgelegd worden

**Comment by ehotting** [comment]
Wordt verduidelijkt middels #79
