### ISSUE TITLE
3.1 geen verwijzing bij open telemetry

### ISSUE THREAD

**Issue by fterpstra** [Logius-standaarden/logboek-dataverwerkingen#61]
Bij de eerste vermelding van het opentelemetry protocol zit geen bron verwijzing. graag toevoegen

**Comment by ehotting** [comment]
@mrtn78 Wat is juiste manier om deze verwijzing formeel & duidelijk op te nemen? Sterke aanbeveling om OTLP te gebruiken dus mag best heel expliciet

**Comment by mrtn78** [comment]
Vooralsnog nemen we een verwijzing op naar https://opentelemetry.io/docs/specs/otlp/
