### ISSUE TITLE
1.3.2 & 3.2.1 TLS bronverwijzing

### ISSUE THREAD

**Issue by fterpstra** [Logius-standaarden/logboek-dataverwerkingen#63]
TLS wordt 2x genoemd zonder verklaring van de afkorting of bronverwijzing. Graag tenminste bronverwijzing toevoegen. Suggestie gebruik https://www.forumstandaardisatie.nl/open-standaarden/tls dan heb je een versieloze verwijzing naar de verplichte standaard. scheelt later in het onderhoud als er nieuwe TLS versies komen.

**Comment by ehotting** [comment]
@mrtn78 Ik wil dit soort verwijzingen eigenlijk uit de Terminologie houden, omdat het niet specifiek voor de standaard is. Hoe kunnen we dat regelen?

**Comment by Nil-NMB01** [comment]
Doorgevoerd: https://github.com/Logius-standaarden/logboek-dataverwerkingen/commit/c62032b3e5f5ada5af93b72de12cbd764cabc3fe
