### ISSUE TITLE
3.2.2 bronverwijzingen

### ISSUE THREAD

**Issue by fterpstra** [Logius-standaarden/logboek-dataverwerkingen#64]
URI en CMDB hebben geen bronverwijzing en worden niet nader verklaard. graag minimaal bronverwijzing toevoegen.

**Comment by ehotting** [comment]
@mrtn78 Ik wil dit soort verwijzingen eigenlijk uit de Terminologie houden, omdat het niet specifiek voor de standaard is. Hoe kunnen we dat regelen?

**Comment by mrtn78** [comment]
Alleen nog in par https://logius-standaarden.github.io/logboek-dataverwerkingen/#interface een verwijzing opnemen voor CMDB, als deze te vinden is.

**Comment by synbiaco** [comment]
ITIL is een beetje uit. Dit staat er gedefinieerd in oud ITIL boek: De CMDB (Configuration Management Database) kan worden gezien als een grote kaartenbak waarin alle IT-productiemiddelen geregistreerd worden, en ook de verschillende relaties tussen de verschillende kaarten beheerd worden. Bron: IT Service Management, een introductie (V2.3, oktober 2000, ITSMF werkgroep 'IT Service Management, een introductie'. https://www.itsmfi.org/

**Comment by Nil-NMB01** [comment]
Hoi @synbiaco check mijn pull request, ik heb toch een verwijzing gevonden.
