### ISSUE TITLE
3.2.2 ID afkorting zonder uitleg

### ISSUE THREAD

**Issue by fterpstra** [Logius-standaarden/logboek-dataverwerkingen#65]
ID wordt als afkorting gebruikt zonder toelichting. Zal IDentifier betekenen neem ik aan. Uitleggen en/of uitschrijven. Mogelijk zelfs een definitie voor opnemen. Uniek ID komt ook terug, is dit een UUID of een GUID of iets anders, is hij betekenisloos of mag betekenisvol ook, wat mag de implementator zelf kiezen? graag toelichten.

**Comment by ehotting** [comment]
Wordt resolved in #79
