### ISSUE TITLE
Gebruik MOET, MAG, AANBEVOLEN

### ISSUE THREAD

**Issue by fterpstra** [Logius-standaarden/logboek-dataverwerkingen#67]
Dit lijkt de Nederlandse vertaling van IETF https://datatracker.ietf.org/doc/html/rfc2119 graag verwijzing hiernaar en korte toelichting van de betekenis en/of mapping Nederlandse termen naar Engelse termin in rfc2119

**Comment by ehotting** [comment]
staat helemaal onderin, @mrtn78 kan je dit gelijktrekken met hoe Logius dit voor alle standaarden doet?
