### ISSUE TITLE
Gegevensmodel opnemen in het Algemene inleidend document

### ISSUE THREAD

**Issue by mrtn78** [Logius-standaarden/logboek-dataverwerkingen#7]
Zie [Canoniek gegevensmodel](https://www.samenwerkruimten.nl/teamsites/project%20verwerkingenlogging/Gedeelde%20%20documenten/Informatieanalyse/Concepten/CanoniekGegevensModel.xlsx?d=w3a3121bbe301485a98ee88f217cda2cf)

**Comment by Nil-NMB01** [comment]
In markdown tabellen maken.

**Comment by synbiaco** [comment]
je kunt ook het word document gebruiken ipv excel

**Comment by Nil-NMB01** [comment]
Eerste tabel overgenomen, maar het ziet er compleet onoverzichtelijk uit in markdown. Met collega's bespreken hoe dit eventueel netter kan.

Link: https://github.com/Logius-standaarden/logboek-dataverwerkingen/blob/develop/CanoniekGegevensmodel.md

**Comment by Nil-NMB01** [comment]
Algemene inleidend document

**Comment by Nil-NMB01** [comment]
Done: https://github.com/Logius-standaarden/logboek-dataverwerkingen_Inleiding/blob/main/CanoniekGegevensmodel.md

**Comment by Nil-NMB01** [comment]
@mrtn78 Zou jij dit willen reviewen en bij goedkeuring willen sluiten?

**Comment by mrtn78** [comment]
ik heb het stuk doorgenomen en wat kleine aanvullingen gedaan voor de leesbaarheid e.d. Wil jij de definities en toelichtingen nogaals checken of deze kloppen? 
resource.version staat nu een onjuiste definitie en verschillende toelichtingen ontbreken nog.
het gegevensmodel is nu opgenomen in de documentstructuur en zichtbaar in [§ 3.2 Canoniek Gegevensmodel](https://logius-standaarden.github.io/publicatie/api/Logboek_Algemeen/#canoniek-gegevensmodel)

**Comment by Nil-NMB01** [comment]
@mrtn78 nogmaals reviewen aub.

**Comment by Nil-NMB01** [comment]
Hoi @mrtn78 zou je hem nogmaals willen reviewen? 😃

**Comment by mrtn78** [comment]
gereviewd
