### ISSUE TITLE
2.1 & 3.4.1 API

### ISSUE THREAD

**Issue by fterpstra** [Logius-standaarden/logboek-dataverwerkingen#70]
API kent geen uitleg en bronvermelding https://www.noraonline.nl/wiki/Application_Programming_Interface_(API)

**Comment by ehotting** [comment]
Zal bronvermelding opnemen, maar zou liever een meer internationale bron aanhalen. Suggesties?

**Comment by ehotting** [comment]
@mrtn78 Ik wil dit soort verwijzingen eigenlijk uit de Terminologie houden, omdat het niet specifiek voor de standaard is. Hoe kunnen we dat regelen?

**Comment by mrtn78** [comment]
@ehotting dit is de beste die ik kan vinden: https://csrc.nist.gov/glossary/term/Application_Programming_Interface.
deze benoemd wel het acroniem API https://datatracker.ietf.org/doc/rfc9315/ maar voegt niets toe.

**Comment by mrtn78** [comment]
> Zal bronvermelding opnemen, maar zou liever een meer internationale bron aanhalen. Suggesties?

Mijn voorkeur is ook een internationale bron en nniet de nora maar he tis lastig ee nverwijzing te vinden. specref biedt ook geen uitkomst.

**Comment by mrtn78** [comment]
Ik heb API uitgeschreven als Application Programming Interface, daarmee is het m.i. ook opgelost
