### ISSUE TITLE
5. voorbeelden - SKreviews

### ISSUE THREAD

**Issue by shayankhan19988** [Logius-standaarden/logboek-dataverwerkingen#72]
- Het proces is een ‘happy flow’ dit betekent dat validaties en eventuele foutsituaties in dit voorbeeld niet in ogenschouw worden genomen.--> na flow een komma*typo
- Bij elk voorbeeld bovenstaande aanpassen

**Comment by Nil-NMB01** [comment]
Changes doorgevoerd: https://github.com/Logius-standaarden/logboek-dataverwerkingen_Inleiding/commit/ccf5d4052b1fe55b89eec8afff65fa9d92885cdb
