### ISSUE TITLE
Voorbeeld applicaties opnemen in de inleiding van de standaard

### ISSUE THREAD

**Issue by mrtn78** [Logius-standaarden/logboek-dataverwerkingen#8]
Zie https://gitlab.com/digilab.overheid.nl/ecosystem/logboek-dataverwerkingen/rva - Register van de verwerkingsactiviteiten
&
Zie https://gitlab.com/digilab.overheid.nl/ecosystem/logboek-dataverwerkingen - Logboek dataverwerkingen

**Comment by Nil-NMB01** [comment]
Bespreken wat hiervan de bedoeling was en waar binnen de inleiding.

**Comment by Nil-NMB01** [comment]
Gaat wel om inleidend document. Nog onduidelijk welk hoofdstuk.

**Comment by Nil-NMB01** [comment]
Linkje overnemen en een beschrijving van de link.

**Comment by Nil-NMB01** [comment]
Staan erin, maar binnen welk hoofdstuk mag het geplaatst worden @mrtn78
