### ISSUE TITLE
typo 'Binnenlandse Zaken' in Standaard 

### ISSUE THREAD

**Issue by ehotting** [Logius-standaarden/logboek-dataverwerkingen#82]
https://github.com/Logius-standaarden/logboek-dataverwerkingen/blob/30cf4f227be2a6bc635de5b4f7136e987d0988f7/config.js#L25

**Comment by mrtn78** [comment]
al gefixed in https://github.com/Logius-standaarden/logboek-dataverwerkingen/pull/36
