### ISSUE TITLE
Aanpassing Inleiding - Architectuur - Berichtenverkeer

### ISSUE THREAD

**Issue by synbiaco** [Logius-standaarden/logboek-dataverwerkingen#98]
**Is:**
Berichtenverkeer / gegevensuitwisseling

Het berichten verkeer met betrekking tot het Logboek dataverwerkingen heeft geen directe connectie met de burger. Wel is het van belang bij opvraag van gegevens bij andere organisaties traceringsdata worden verstuurd en opgeslagen in het Logboek zodat altijd duidelijk wat de bron is van data die verwerkt zijn. Deze standaard biedt een traceringsmethodiek aan zodat de gegevensuitwisseling tussen organisaties soepel en geautomatiseerd kan verlopen.

**Moet worden:**
Berichtenverkeer / gegevensuitwisseling

Het berichten verkeer met betrekking tot het Logboek dataverwerkingen heeft geen directe connectie met de burger. Wel is het van belang bij opvraag van gegevens bij andere organisaties traceringsdata worden verstuurd en opgeslagen in het Logboek zodat altijd duidelijk wat de bron is van data die verwerkt zijn. Deze standaard biedt een traceringsmethodiek aan zodat de gegevensuitwisseling tussen organisaties _vastgelegd en verantwoord kan worden._

**Comment by Nil-NMB01** [comment]
Change doorgevoerd: https://github.com/Logius-standaarden/logboek-dataverwerkingen_Inleiding/commit/d63790b5df9ea7b2a84ef18f7913c236b922a162
