### ISSUE TITLE
Aanpassing Inleiding - Architectuur - Data/gegevens

### ISSUE THREAD

**Issue by synbiaco** [Logius-standaarden/logboek-dataverwerkingen#99]
Is:

De Nederlandse Basisregistraties vervullen een essentiële rol in het vastleggen en gecontroleerd beheren van data. Organisaties kunnen aan elkaar data ter beschikking te stellen vanuit ‘kernregistraties’. Deze data staan gedefinieerd in het [Federatief Datastelsel](https://realisatieibds.nl/groups/view/0056c9ef-5c2e-44f9-a998-e735f1e9ccaa/federatief-datastelsel/wiki/view/642216bb-ff52-4ce0-98fb-cb2aa8fda7c1/wat-houdt-het-federatief-datastelsel-in). De standaard Logboek dataverwerkingen biedt een richtlijn voor het loggen van verwerkte data van al deze basisregistraties.

Moet worden:
De Nederlandse Basisregistraties vervullen een essentiële rol in het vastleggen en gecontroleerd beheren van data. Organisaties kunnen aan elkaar data ter beschikking te stellen vanuit ‘kernregistraties’. De standaard Logboek dataverwerkingen biedt een richtlijn voor het loggen van verwerkte data van al deze basisregistraties.

Zin _Deze data staan gedefinieerd in het [Federatief Datastelsel](https://realisatieibds.nl/groups/view/0056c9ef-5c2e-44f9-a998-e735f1e9ccaa/federatief-datastelsel/wiki/view/642216bb-ff52-4ce0-98fb-cb2aa8fda7c1/wat-houdt-het-federatief-datastelsel-in)._ verwijderen

**Comment by Nil-NMB01** [comment]
Change doorgevoerd: https://github.com/Logius-standaarden/logboek-dataverwerkingen_Inleiding/commit/637770f6874d90b15a7936b606ac38c5ab5b54ef
